### ISSUE TITLE
Açık Kaynak Web Site 1.0 Yol Haritası

### ISSUE THREAD

**Issue by eserozvataf** [acikkaynak/acikkaynak-website#30]
Tarihleri maalesef oldukça esnek Sprint 1'imizin sonuna gelirken, Açık Kaynak Projelendirme ( #17 )'de başlatılan sürecin çıktısını bir yol haritası haline getirmeyi başarabildik.

Aşağıdaki gibi bir yol haritası mevcut, tüm maddeler için de birer issue açılıyor olacak:

- [x] Koda Katkıyı Kolaylaştırmak için README'e Yönlendirmelerin Eklenmesi ( #31 )
- [x] Yeni Tasarım'ın Figma'ya Geçirilmesi ( #32 )
- [x] Yeni Tasarım ve Uygulanması ( #29 )
- [x] Semantic UI React'ı Yeni Tasarım Diline Adapte Etmek ( #33 )
- [ ] Alt Sayfaların UX Tasarımlarının Oluşturulması ( #34 )
- [ ] Web Sitesinde Yer Alan Eksik İçeriklerin Tamamlanması ( #35 )
- [ ] Haberler Bölümü ( #36 )
- [ ] GitHub ile Login ( #37 )
- [ ] GitHub ile Login için Kullanıcı Sözleşmesinin Hazırlanması ( #38 )
- [ ] İstatistikler Bölümü ( #39 )
- [ ] Backend API ile Web Sayfalarını Bağlamak ( #40 )

Direkt ilgili gerekli aktarımlar konusunda yardım sağlamak için, üstlenmek istediğiniz madde olursa lütfen burada belirtin :)
